services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sns-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET=${SECRET}
      - API_DOMAIN=${API_DOMAIN}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - sns-network
  db:
    image: postgres:15-alpine
    container_name: sns-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    restart: always
    networks:
      - sns-network

networks:
  sns-network: